### ISSUE TITLE
Create new "slider_training" app

### ISSUE THREAD

**Issue by ianchadd** [ianchadd/va#1]
Create a new app that does the following:

- Takes the place of pt1 (i.e. if there is anything to pass from pt0 to pt1, slider_training should function in a similar way)
- Split Intro from pt1 into 4 separate pages. One for each of the Examples and one with just the comprehension questions that are at the end of the examples in the current Into template. 
- It should function similar to pt1 in that it should expect pt2 to come after it and should save/pass along any relevant variables

**Comment by mcdaij** [comment]
I'll get this tested and submitted for you by Thursday morning at the latest, hopefully tomorrow morning.
