### ISSUE TITLE
For VA interaction app, structure as "rounds" not as overall timer

### ISSUE THREAD

**Issue by ianchadd** [ianchadd/va#10]
- [x] get rid of timer display
- [x] SUBJECT TURN: do not display VA avatar; only display 10 second timer for own round
- [x] VA TURN: show VA avatar; grey out slider; display 10 second timer for VA round
- [x] Display VA success/failure message for 3 seconds before moving on to Subject round (before 10 second timer starts)

**Comment by maddy0314** [comment]
Timer display changed to turn timer. VA success/failure msg duration changed locally, will update on next commit.
