### ISSUE TITLE
Front end edits

### ISSUE THREAD

**Issue by ianchadd** [ianchadd/va#17]
- [x] remove "VA Task 1"
- [x] center "It is your turn/it's the VA's turn" on the screen
- [x] center time remaining and put just above the slider puzzle
- [x] change text to "Your Turn" and "VA Turn" from "it is your turn [...]"
- [x] move success/failure text to just below slider puzzle, center it, and increase font size for salience.

**Comment by maddy0314** [comment]
Done, see most recent commit.
