### ISSUE TITLE
Add treatment vars

### ISSUE THREAD

**Issue by ianchadd** [ianchadd/va#3]
- add "treatment" to session config
- one option: "failure_badmove" is what you have for VA actions now (failure = VA makes a sub-optimal move)
- another option (what we plan on using for now): "failure_nomove" where failure = VA makes no move at all during their turn

**Comment by maddy0314** [comment]
Done! See most recent commit - toggle session level variable 'failure_tracking' to 0 for no move or 1 for bad move.
