### ISSUE TITLE
add session config for gender treatment

### ISSUE THREAD

**Issue by ianchadd** [ianchadd/va#5]
add session var "treatment_gender" where the options are {Male, Female, Neutral}. We'll use this later for text/avatars for the VA.

**Comment by maddy0314** [comment]
To be honest, the way the avatars are written in kind of dictates where this variable should go. I'm holding off on this until I can get text and an avatar to reliably show up on screen.

**Comment by maddy0314** [comment]
Also has been done. See session variable 'pt1gender' in settings.py. Can easily be set to a die roll to implement random VA gender, and duplicated for other treatments if VA gender independence between treatments is desired.
