### ISSUE TITLE
add X second turns for subject and VA

### ISSUE THREAD

**Issue by ianchadd** [ianchadd/va#6]
- let X = 10 seconds in the demo, but X should be configurable at the session level
- X seconds for participant turn to make their move. They can only make one move, grey out the slider once the move is made. They still have to wait the entire X seconds for their turn to elapse.
- X seconds for VA turn. Slider puzzle should be greyed out during the VA turn and untouchable.

**Comment by maddy0314** [comment]
I FIGURED OUT HOW TO MAKE THIS WORK IN NATIVE JS
I'm finishing my implementation of it now, and I'll commit ASAP. It's a really elegant solution IMO. I'm proud of it. And I didn't need ChatGPT. :)))

**Comment by maddy0314** [comment]
It works fully! See new commit.
