### ISSUE TITLE
question: how does VA choose a move in the event of failure?

### ISSUE THREAD

**Issue by ianchadd** [ianchadd/va#7]
for the "bad move" algo code, does the VA choose randomly from the set of **all moves** or **suboptimal moves**? 

Asked another way, in the event of a failure, is it possible that the randomly chosen VA move ends up being optimal?

**Comment by maddy0314** [comment]
Right now it chooses from the set of suboptimal moves. If you don't like that it would be trivial to change - let me know if you'd rather it be the set of all moves.

**Comment by ianchadd** [comment]
this is desired, just wanted to clarify. thanks!
